config/routes.rb
Rails.application.routes.draw do
  get 'proyecto/new'
  post 'proyecto/create'
  get 'proyecto/dashboard'
  root 'proyecto#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/proyecto.rb
class Proyecto < ApplicationRecord
    validates :name, :description, :state, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/proyecto_controller.rb
class ProyectoController < ApplicationController
  def new
  end

  def create
    @project = Proyecto.create(name: params[:name], description: params[:description], date_start: params[:date_start], date_end: params[:date_end], state: params[:state])
  end

  def dashboard
    if params[:state].present?
      @projects = Proyecto.where('state = ?', params[:state])
    else
      @projects = Proyecto.all
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/proyecto_helper.rb
module ProyectoHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/proyecto/create.html.erb
<%= link_to 'Volver al Inicio', root_path %><br>
<% if @project.errors.any? %>
    <div id="error_explanation">
        <h2>
            No se puede guardar el post, por las siguientes razones
        </h2>
        <ul>
            <% @project.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
    <% else %>
    <h1>¡Registro exitoso!</h1>
<% end  %>

app/views/proyecto/dashboard.html.erb
<table class="table">
    <tr>
        <th>Nombre</th>
        <th>Descripcion</th>
        <th>Fecha de Inicio</th>
        <th>Fecha de Fin</th>
        <th>Estado</th>
    </tr>
    <% @projects.each do |p| %>
        <tr>
            <td><%= p.name %></td>
            <td><%= p.description %></td>
            <td><%= p.date_start %></td>
            <td><%= p.date_end %></td>
            <td><%= p.state %></td>
        </tr>
    <% end %>
</table>
<form>
        <label for="state">Estado</label>
        <select name="state">
            <option value="propuesta">propuesta</option>
            <option value="progreso">progreso</option>
            <option value="terminado">terminado</option>
        </select>
        <button type="submit" class="btn btn-primary">Buscar</button>
</form>




<%= link_to 'Volver al Inicio', root_path %><br>

app/views/proyecto/new.html.erb
<form action="/proyecto/create" method="POST">
    <input type="hidden" name="authenticity_token" value="<=% form_authenticity_token %>">

    <div class="form-group">
        <label for="name">Nombre</label>
        <input name="name" class="form-control">
    </div>

    <div class="form-group">
        <label for="description">Descripcion</label>
        <input name="description" class="form-control">
    </div>

    <div class="form-group">
        <label for="date_start">Fecha de inicio</label>
        <input type='date' name="date_start" class="form-control"> </input>
    </div>
    
    <div class="form-group">
        <label for="date_end">Fecha de fin</label>
        <input type='date' name="date_end" class="form-control"> </input>
    </div>

    <div class="form-group">
        <label for="state">Estado</label>
        <select name="state">
            <option value="propuesta">propuesta</option>
            <option value="progreso">progreso</option>
            <option value="terminado">terminado</option>
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Enviar</button>
</form>

<%= link_to 'Ir al Dashboard', proyecto_dashboard_path %><br>